import { chmodSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { readText, removeIfExists, renameIfExists, replaceInTree, writeText } from './lib/fs';
import { git, isGitRepo, runInherit } from './lib/git';

interface HarnessManifest {
  name: string;
  version: string;
  standard: string;
}

/**
 * Git-native provenance written at `just init` time. Captures the
 * canonical-template repo + commit the consumer forked at, with NO
 * lab-side state — the lab is R&D only and not a live upstream. See
 * `docs/adrs/ADR-0015-cha-sync-source-of-truth.md`.
 */
interface HarnessProvenance {
  schemaVersion: '1.0';
  mode: 'fresh';
  template: string;
  templateVersion: string;
  standardVersion: string;
  canonical_repo: string;
  canonical_commit: string;
  forked_at: string;
}

const DEFAULT_CANONICAL_REPO = 'https://github.com/syntropic137/harness-app-template';

export interface InitOptions {
  cwd?: string;
  force?: boolean;
  now?: Date;
  verify?: boolean;
}

const PROJECT_RE = /^[a-z0-9][a-z0-9-]{0,213}$/;

export function validateProjectName(projectName: string): void {
  if (!PROJECT_RE.test(projectName)) {
    throw new Error('project name must match npm-safe pattern ^[a-z0-9][a-z0-9-]*$ and be <= 214 chars');
  }
}

function removeTemplateReadmeBlock(cwd: string): void {
  const path = join(cwd, 'README.md');
  if (!existsSync(path)) return;
  const original = readText(path);
  const updated = original.replace(/\n?<!-- TEMPLATE-DOC-START -->[\s\S]*?<!-- TEMPLATE-DOC-END -->\n?/m, '\n');
  if (updated !== original) {
    writeText(path, updated);
  }
}

function updateRootPyproject(cwd: string, projectName: string): void {
  const path = join(cwd, 'pyproject.toml');
  if (!existsSync(path)) return;
  const original = readText(path);
  // The root pyproject declares the virtual uv workspace; its name must
  // NOT collide with the inner Python member's name (otherwise
  // `uv sync` refuses with "two workspace members are both named X").
  // Suffix the root with `-monorepo` to keep it distinct from the
  // `${projectName}-python` member that `replaceInTree` rewrites inside
  // `ws_apps/${projectName}-python/pyproject.toml`.
  const updated = original.replace(/^name = "agentic-harness-monorepo"$/m, `name = "${projectName}-monorepo"`);
  if (updated !== original) {
    writeText(path, updated);
  }
}

function updateHarnessComposeName(cwd: string, projectName: string): void {
  const path = join(cwd, 'harness/observability/compose.harness.yml');
  if (!existsSync(path)) return;
  const original = readText(path);
  const updated = original.replace(/^name:\s*agentic-harness-monorepo\s*$/m, `name: ${projectName}`);
  if (updated !== original) {
    writeText(path, updated);
  }
}

/* v8 ignore next 3 */
function shellQuote(value: string): string {
  return `'${value.replaceAll("'", "'\\''")}'`;
}

/* v8 ignore next 24 */
function installGitHooks(cwd: string): void {
  const globalHooksPath = git(['config', '--global', '--get', 'core.hooksPath'], { cwd, allowFailure: true });
  runInherit('pnpm', ['exec', 'lefthook', 'install', '--force'], cwd);
  git(['config', '--local', '--unset', 'core.hooksPath'], { cwd, allowFailure: true });

  if (!globalHooksPath) {
    return;
  }

  const wrapper = `#!/usr/bin/env bash
# Auto-generated by scripts/init.ts on \`just init\`.
# Chains the operator/global attribution hook configured via core.hooksPath,
# while keeping this repo on .git/hooks so lefthook also fires.
set -euo pipefail
GLOBAL_HOOK=${shellQuote(globalHooksPath)}/prepare-commit-msg
if [ -x "$GLOBAL_HOOK" ]; then
  "$GLOBAL_HOOK" "$@"
fi
`;
  const hookPath = join(cwd, '.git/hooks/prepare-commit-msg');
  writeText(hookPath, wrapper);
  chmodSync(hookPath, 0o755);
  console.log(`hooks: chained global prepare-commit-msg from ${globalHooksPath}; local .git/hooks remains active`);
}

/**
 * Resolve the canonical repo URL. Priority:
 *   1. `git remote get-url upstream` (the canonical sync remote, if the
 *      user already wired it up before `just init`).
 *   2. `git remote get-url origin` (the URL the consumer cloned/forked
 *      from — typically this IS the canonical repo for "Use this
 *      template" flows).
 *   3. Hard-coded fallback to `syntropic137/harness-app-template`.
 *
 * Returns the URL as-is; consumers can edit `.harness-provenance.json`
 * once if they need a different value (the file is immutable after init
 * per the `update.ts` guard).
 */
function resolveCanonicalRepo(cwd: string): string {
  const upstream = git(['remote', 'get-url', 'upstream'], { cwd, allowFailure: true });
  if (upstream) return upstream;
  const origin = git(['remote', 'get-url', 'origin'], { cwd, allowFailure: true });
  if (origin) return origin;
  return DEFAULT_CANONICAL_REPO;
}

/**
 * Resolve the canonical commit the consumer forked at. This is just
 * `HEAD` at init time — for "Use this template" and fork flows, HEAD
 * IS the canonical commit you started from. Returns 'unknown' if HEAD
 * doesn't yet exist (degenerate edge case, e.g. an empty repo).
 */
function resolveCanonicalCommit(cwd: string): string {
  return git(['rev-parse', 'HEAD'], { cwd, allowFailure: true }) || 'unknown';
}

export function writeHarnessProvenance(cwd: string, now = new Date()): HarnessProvenance {
  const manifest = JSON.parse(readText(join(cwd, 'harness.manifest.json'))) as HarnessManifest;
  const provenance: HarnessProvenance = {
    schemaVersion: '1.0',
    mode: 'fresh',
    template: manifest.name,
    templateVersion: manifest.version,
    standardVersion: manifest.standard,
    canonical_repo: resolveCanonicalRepo(cwd),
    canonical_commit: resolveCanonicalCommit(cwd),
    forked_at: now.toISOString(),
  };
  writeText(join(cwd, '.harness-provenance.json'), `${JSON.stringify(provenance, null, 2)}\n`);
  return provenance;
}

export function initProject(projectName: string, options: InitOptions = {}): string[] {
  const cwd = options.cwd ?? process.cwd();
  validateProjectName(projectName);

  if (isGitRepo(cwd) && !options.force) {
    const dirty = git(['status', '--porcelain'], { cwd });
    if (dirty) {
      throw new Error('working tree is not clean; rerun with --force to initialize anyway');
    }
  }

  const replacements: Array<[string, string]> = [
    ['@example/typescript', `@${projectName}/typescript`],
    ['@example/python', `@${projectName}/python`],
    ['@example/rust', `@${projectName}/rust`],
    ['example-typescript', `${projectName}-typescript`],
    ['example-python', `${projectName}-python`],
    ['example-rust', `${projectName}-rust`],
  ];
  const changed = replaceInTree(cwd, replacements);

  renameIfExists(join(cwd, 'ws_apps/example-typescript'), join(cwd, `ws_apps/${projectName}-typescript`));
  renameIfExists(join(cwd, 'ws_apps/example-python'), join(cwd, `ws_apps/${projectName}-python`));
  renameIfExists(join(cwd, 'ws_apps/example-rust'), join(cwd, `ws_apps/${projectName}-rust`));

  updateRootPyproject(cwd, projectName);
  updateHarnessComposeName(cwd, projectName);
  removeTemplateReadmeBlock(cwd);
  removeIfExists(join(cwd, 'TEMPLATE.md'));
  removeIfExists(join(cwd, '.github/ISSUE_TEMPLATE/template-question.md'));
  writeHarnessProvenance(cwd, options.now);

  /* v8 ignore next 7 */
  if (options.verify !== false) {
    runInherit('bun', ['--version'], cwd);
    runInherit('pnpm', ['install'], cwd);
    runInherit('cargo', ['check'], cwd);
    runInherit('uv', ['sync'], cwd);
    installGitHooks(cwd);
  }

  return changed;
}

export function parseCli(argv: string[]): { projectName: string; force: boolean; verify: boolean } {
  const force = argv.includes('--force');
  const noVerify = argv.includes('--no-verify');
  const projectName = argv.find((arg) => !arg.startsWith('--'));
  if (!projectName) {
    throw new Error('usage: bun run scripts/init.ts <project-name> [--force] [--no-verify]');
  }
  return { projectName, force, verify: !noVerify };
}

/* v8 ignore next 11 */
if (import.meta.url === `file://${process.argv[1]}`) {
  try {
    const { projectName, force, verify } = parseCli(process.argv.slice(2));
    initProject(projectName, { force, verify });
    console.log(`initialized ${projectName}`);
    console.log('next: just bootstrap && just test');
  } catch (error) {
    console.error(`error: ${error instanceof Error ? error.message : String(error)}`);
    process.exit(1);
  }
}
